<a href="https://colab.research.google.com/github/dionysus98/l_torch/blob/main/00_torch_fundm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [ ]:
## 00. Pytorch Fundamentals
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.3.0+cu121


In [ ]:
t = torch.tensor([[[1, 8],[3, 8]], [[1, 2], [3, 4]]])

print(t.shape)
print(t.size())
print(t.dim())


x = torch.arange(0, 100, 1) # random tensor
[x.argmin(), x.argmax()]

torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
3


[tensor(0), tensor(99)]

## Tensor

In [ ]:
# reshaping, stacking, viewing, squeeze, permute

x = torch.arange(1.,11.) # random tensor
x.shape

torch.Size([10])

In [ ]:
# reshape [returns a new tensor]
x_reshape = x.reshape(5, 2)
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# View [shares the same memory as the original input, a pointer]
z = x.view(1,9)

In [ ]:
# stacked
x_stacked = torch.stack([x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[ 1.,  1.],
         [ 2.,  2.],
         [ 3.,  3.],
         [ 4.,  4.],
         [ 5.,  5.],
         [ 6.,  6.],
         [ 7.,  7.],
         [ 8.,  8.],
         [ 9.,  9.],
         [10., 10.]]),
 torch.Size([10, 2]))

## Squeeze & Unsqueeze

In [ ]:
# squeeze [returns a tensor, with all the `1` dimension removeed]
# unsqueeze [returns a tensor, with a new dimension added]
x_reshaped = x.reshape(1, 10)
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_reshaped.unsqueeze(0)
x_squeezed, x_squeezed.shape, x_unsqueezed, x_unsqueezed.shape, x_reshaped, x_reshaped.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]]),
 torch.Size([1, 1, 10]),
 tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

## Permute

In [ ]:
# Permute [rearrange tensor dim in a specified order, returns a torch.view]
y = torch.randn(2, 3, 5)
y_muted = y.permute([2, 1 ,0])
y_muted.shape, y.shape

(torch.Size([5, 3, 2]), torch.Size([2, 3, 5]))

## Indexing

In [ ]:
# TRAVERSE

# x = torch.arange(1,10).reshape(3,3).unsqueeze(0)
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0, 1, 2]

tensor(6)

In [ ]:
print(x[:, 1, :] == x[:, 1]) # go to the inner row, and retriever all

tensor([[True, True, True]])


## Torch  && Numpy

In [ ]:
npa = np.arange(1.,8.)
t = torch.from_numpy(npa) # create a f64
t= t.type(torch.float32)
npa, npa.dtype, t, t.dtype, t.numpy() # tensor to numpy

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32,
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

## Reproducibility (seeding random)

In [ ]:
rand_a = torch.randn(3, 4)
rand_b = torch.randn(3, 4)
rand_a, rand_b, rand_a == rand_b

(tensor([[ 0.8446, -0.3567,  1.5678,  0.3369],
         [ 0.2734, -0.4002, -1.1831,  1.3153],
         [-0.1035,  1.1451, -0.7349, -0.8811]]),
 tensor([[-1.2678,  0.7899, -0.5958, -1.8741],
         [-0.7738,  0.1709,  0.1819, -1.4499],
         [ 2.3740, -2.3305, -0.0749, -0.1183]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
RAND_SEED = 17

torch.manual_seed(RAND_SEED)
rand_c = torch.randn(3, 4)

torch.manual_seed(RAND_SEED)
rand_d = torch.randn(3, 4)

rand_c, rand_d, rand_c == rand_d

(tensor([[-1.4135,  0.2336,  0.0340,  0.3499],
         [-0.0145, -0.6124, -1.1835, -1.4831],
         [ 1.8004,  0.0096,  0.1534, -2.6631]]),
 tensor([[-1.4135,  0.2336,  0.0340,  0.3499],
         [-0.0145, -0.6124, -1.1835, -1.4831],
         [ 1.8004,  0.0096,  0.1534, -2.6631]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

## working with GPUs

In [ ]:
#check for GPU access
!nvidia-smi

In [1]:
import torch
torch.cuda.is_available()

True

In [3]:
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DEVICE,

('cuda',)

### putting tensors on GPU

In [4]:
# cpu
t = torch.tensor([1,2,3])
t, t.device

(tensor([1, 2, 3]), device(type='cpu'))

In [5]:
# gpu
t_gpu = t.to(DEVICE)
t_gpu,

(tensor([1, 2, 3], device='cuda:0'),)

In [8]:
t_gpu.to("cpu").numpy() # numpy only works with CPU
t_gpu.cpu().numpy() # numpy only works with CPU

array([1, 2, 3])